### ISSUE TITLE
Separate out audio functionality

### ISSUE THREAD

**Issue by dsvensson** [librespot-org/librespot-java#234]
It would be great if audio functionality would be split out into a separate module to enable headless mode where the use is only data rather than playback.

**Comment by devgianlu** [comment]
What do you mean by data?

**Comment by dsvensson** [comment]
I guess I interpreted this as a library rather than an application and it was a bit unexpected that for example the argument to FileConfiguration was the actual string `"--conf-file=..."`, and that it opened an audio device, but perhaps **lib**_respot_ is more thought of as **libre**_spot_, completely geared towards reproducing a Spotify Desktop Client like app?

I was just interested in writing a cli to search with. Seems like setting the `[player] output = "STDOUT"` got rid of the mixer probing. Haven't tried running it with a headless JVM yet, but perhaps that'll work now.

Still having some issues with shutdown, seems like some OkHttp thread lingers even after calling session.close().

**Comment by devgianlu** [comment]
You're right, the name is a bit confusing because this is a fully fletched player with library features all merged together. While I like the idea of separating the API part of the project into a different module, I need to combat piracy (low effort piracy) by avoiding to expose crucial parts which can be exploited. That is feasible though.

Setting the output to `STDOUT` will get rid of the mixer problem and won't output anything as long as you don't ask it to.

> Still having some issues with shutdown, seems like some OkHttp thread lingers even after calling session.close().

As I don't use the project as a library specifically I tend to leave those behind, please open a separate issue or PR and I'll sort it out.

**Comment by dsvensson** [comment]
Humm.... I wonder if it performs `close()` on stdout then when issuing `session.close()`, last line of that function, `Closed session. {deviceId: %s}` , never reaches the console :)

**Comment by devgianlu** [comment]
It was indeed closing `STDOUT` so I fixed that, but the issue remains if the library is closed with `Ctrl-C` because the logger threads are shutdowned too.

**Comment by devgianlu** [comment]
Closing in favor of #245.
