### ISSUE TITLE
[api] Allow better control of relative volume change

### ISSUE THREAD

**Issue by xvello** [librespot-org/librespot-java#272]
**Is your feature request related to a problem? Please describe.**

Hello! For a home automation use case, I need to change the volume several steps at a time (eg. +5 or -2). I'd love the http api to allow this.

**Describe the solution you'd like**

Either:
  - Allow a `steps` param to `volume-up` and `volume-down` to specify a step count, the default being the current value of 1
  - Allow the `set-volume` to work in relative volume with an additional parameter, the default staying absolute

**Describe alternatives you've considered**

- I am currently looping on the client side and issuing one http request per step
- I investigated getting the current volume, to issue a single `set-volume` request, but it does not seem available, and would require two requests anyway

**Additional context**

I'd be happy to contribute a PR after we discuss of what method to go forward with.

**Comment by devgianlu** [comment]
I think the best option would be add an optional parameter `step` to `set-volume` which can be negative or positive and allows  to decrement (or increment) the volume. It could also be applied to `volume-up` or `volume-down`, but then, in my opinion, it would be confusing because the step value could be negative or positive. I'd go with the first approach I mentioned.

I can't do it myself right now, but I can eventually review a PR. Thanks.

**Comment by xvello** [comment]
https://github.com/librespot-org/librespot-java/pull/273 implements this and is running on my server, thanks a lot for maintaining this project :bow:
