### ISSUE TITLE
Playback stops 10 seconds before end of every track

### ISSUE THREAD

**Issue by loeffelpan** [librespot-org/librespot-java#47]
Log says preloading is ready. Then Ping, Pong and stop.
No errors.

**Comment by crsmoro** [comment]
just a bit more information, when the preload is disabled the current music don't stop, but when the next music starts there is no sound, but everything else is normal..

**Comment by devgianlu** [comment]
That issue was introduced by Spotify sending some "false" pause actions (don't know what's happening). Ignoring these messages fixed it.

**Comment by crsmoro** [comment]
i couldnt reproduce either, i don't think that problem was librespot related, i think was on spotify's side..
i noticed this problem with spotify's client too, but all of sudden no more...
now a funny thing about this 'false pause' actions, totally screw up my routine: 
* listening some songs on my laptop
* pause and leave (let it open)
* go to my car, car connects to iphone via bluetooth
* play on spotify automatically
* after a second or so, no sound in the car
* keeps showing it's playing on iphone
* but it's actually playing on my laptop where the client was in pause

that didnt happen before the 'false pause' actions...
i really don't know why spotify did this action..
