### ISSUE TITLE
Strange behaviour

### ISSUE THREAD

**Issue by loeffelpan** [librespot-org/librespot-java#78]
Thanks for you great work and lightning fast support.
Please take a look at this video. It's a screen capture from my iPhone which shows strange behaviour of Spotify while connecting/connected with librespot. Same thing with other spotify-clients (e. g. on Win10 or my iPad). Any idea why the player hides for a few moments when connecting or skipping?
Doesn't happen when player goes to the next track by itself.
Doesn‘t happen with other spotify-clients connected (e. g. Win10 with iPad/iPhone).

https://photos.app.goo.gl/2PfTt4sfvXf5HAFA7

**Comment by devgianlu** [comment]
That's because of the loading state. When librespot is loading a song, it triggers the loading state to let the client know it is doing something. Unlucky Spotify makes the entire UI disappear. 

I should probably make this optional so that users with slower connections can enable this to avoid state corruption.

**Comment by elganzua124** [comment]
I had the same issue on Android. Even with good connection, but with the last update of Spotify on Android the problem just disappeared.

**Comment by devgianlu** [comment]
This can now be toggled with `player.enableLoadingState`.
